name: sgx_client
description: A new flutter plugin project.
version: 0.3.2+1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  hex: ^0.2.0
  pem: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: network.abmatrix.sgx_client
        pluginClass: SgxClientPlugin
      ios:
        pluginClass: SgxClientPlugin

ffigen:
  output: lib/src/bindings.dart
  headers:
    entry-points:
      - cert/target/bindings.h
  name: VerifyBindings 
  description: Dart bindings to call veirfy functions
